author: Jeff Kelley
author_url: https://jeffkelley.org
github_url: https://github.com/Detroit-Labs/BottomSheetPresentation
root_url: https://detroit-labs.github.io/BottomSheetPresentation/
module: BottomSheetPresentation
